version: '3.9'
services:
  million_music_db:
    container_name: million_music_db
    build:
      context: ./web
      target: base
    ports:
      - 12000:3000
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./web:/workspace:cached
      - /workspace/node_modules